import React, { useState } from 'react';
import {
    X, FileText, CalendarBlank, ChartLine, Package,
    ShieldCheck, Warning, DownloadSimple, ShareNetwork,
    CheckCircle, Clock, CaretRight, Info, Camera,
    Users, HardHat, CloudSun, GitDiff, Lightning,
    FilePdf, FileXls, FileCsv, PaperPlaneTilt, Lock
} from '@phosphor-icons/react';
import { motion, AnimatePresence } from 'framer-motion';

const GenerateReportModal = ({ onClose, projects = [] }) => {
    const [reportType, setReportType] = useState('Progress');
    const [config, setConfig] = useState({
        project: '',
        site: 'All Blocks',
        range: 'Daily',
        date: new Date().toISOString().split('T')[0],
        includePhotos: true,
        includeRemarks: true,
        trade: 'Civil',
        priority: 'Medium',
        format: 'PDF'
    });
    const [isGenerating, setIsGenerating] = useState(false);
    const [isLocked, setIsLocked] = useState(false);
    const [step, setStep] = useState(1); // 1: Select Type, 2: Configure/Preview

    const reportTypes = [
        { id: 'Progress', label: 'Progress Report', desc: 'Activity-wise progress, milestones & status.', icon: <ChartLine size={24} />, color: '#2563eb' },
        { id: 'SDR', label: 'Daily / Weekly Site Report', desc: 'Labor, materials, equipment & weather impact.', icon: <FileText size={24} />, color: '#059669' },
        { id: 'Delay', label: 'Schedule & Delay Report', desc: 'Slipped activities & recovery plans.', icon: <Clock size={24} />, color: '#dc2626' },
        { id: 'Material', label: 'Material Usage Report', desc: 'Consumption analysis & wastage tracking.', icon: <Package size={24} />, color: '#d97706' },
        { id: 'Quality', label: 'Quality & Inspection', desc: 'Checklist results & NCR summary.', icon: <ShieldCheck size={24} />, color: '#7c3aed' },
        { id: 'Safety', label: 'Safety & Hazard Report', desc: 'Hazards, corrective actions & compliance.', icon: <Warning size={24} />, color: '#ef4444' },
        { id: 'Resource', label: 'Resource Utilization Report', desc: 'Labor productivity & equipment idle time.', icon: <Users size={24} />, color: '#0ea5e9' },
        { id: 'Instruction', label: 'Issue & Instruction Report', desc: 'Instructions issued & site compliance status.', icon: <PaperPlaneTilt size={24} />, color: '#f59e0b' },
        { id: 'Trend', label: 'Comparative / Trend Report', desc: 'Week-on-week progress & site comparisons.', icon: <GitDiff size={24} />, color: '#10b981' },
        { id: 'AI-Insight', label: 'AI-Assisted Insight Report', desc: 'Risk predictions & bottleneck analysis.', icon: <Lightning size={24} />, color: '#6366f1' }
    ];

    const handleGenerate = () => {
        setIsGenerating(true);
        setTimeout(() => {
            setIsGenerating(false);
            alert(`${reportType} Report generated as ${config.format}. File auto-saved to Command Vault.`);
            onClose();
        }, 2000);
    };

    const renderReportHeader = () => (
        <div style={{ padding: '20px', background: '#0f172a', borderRadius: '12px 12px 0 0', color: 'white' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <div>
                    <h3 style={{ margin: 0, fontSize: '1.25rem', fontWeight: 900 }}>{reportTypes.find(t => t.id === reportType)?.label}</h3>
                    <div style={{ fontSize: '0.8rem', color: '#94a3b8', marginTop: '4px' }}>Project: {projects.find(p => p._id === config.project)?.name || 'Real Estate Sector 4'}</div>
                </div>
                <div style={{ textAlign: 'right' }}>
                    <div style={{ fontSize: '0.7rem', fontWeight: 800, color: '#94a3b8' }}>GENERATED BY (ENGINEER)</div>
                    <div style={{ fontSize: '0.85rem', fontWeight: 700 }}>Er. Rajesh Kumar</div>
                    <div style={{ fontSize: '0.7rem', color: '#64748b' }}>{new Date().toLocaleString()}</div>
                </div>
            </div>
        </div>
    );

    const renderReportFooter = () => (
        <div style={{ padding: '20px', borderTop: '1px solid #e2e8f0', background: '#f8fafc', borderRadius: '0 0 12px 12px' }}>
            <div style={{ marginBottom: '15px' }}>
                <div style={{ fontSize: '0.7rem', fontWeight: 800, color: '#64748b', marginBottom: '8px' }}>ENGINEER OBSERVATIONS</div>
                <div style={{ fontSize: '0.85rem', color: '#1e293b', fontStyle: 'italic', background: 'white', padding: '12px', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
                    Observations gathered from site log 24-B. Structural compliance verified for current phase.
                </div>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
                <div style={{ padding: '10px', background: '#fef2f2', border: '1px solid #fee2e2', borderRadius: '8px', textAlign: 'center' }}>
                    <div style={{ fontSize: '0.65rem', fontWeight: 800, color: '#991b1b' }}>APPROVAL STATUS</div>
                    <div style={{ fontSize: '0.85rem', fontWeight: 900, color: '#ef4444' }}>PENDING REVIEW</div>
                </div>
                <div style={{ padding: '10px', background: isLocked ? '#f8fafc' : '#f1f5f9', border: '1px solid #e2e8f0', borderRadius: '8px', textAlign: 'center' }}>
                    <div style={{ fontSize: '0.65rem', fontWeight: 800, color: '#64748b' }}>SECURITY POLICY</div>
                    <div style={{ fontSize: '0.85rem', fontWeight: 900, color: isLocked ? '#059669' : '#475569', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '5px' }}>
                        {isLocked ? <CheckCircle size={14} weight="fill" /> : <Lock size={14} />}
                        {isLocked ? 'REPORT LOCKED & SIGNED' : 'AUTO-LOCKED ON APPROVAL'}
                    </div>
                </div>
            </div>
            {!isLocked && (
                <button
                    onClick={() => {
                        setIsLocked(true);
                        alert('Report successfully digitally signed and locked for audit trail.');
                    }}
                    style={{ width: '100%', marginTop: '15px', padding: '10px', background: '#0f172a', color: 'white', borderRadius: '8px', border: 'none', fontWeight: 800, fontSize: '0.8rem', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px' }}
                >
                    <CheckCircle size={18} weight="bold" /> Sign & Lock Document
                </button>
            )}
            <div style={{ textAlign: 'center', fontSize: '0.65rem', color: '#94a3b8', marginTop: '15px' }}>
                © REALITY OS REPORT ENGINE • AUTO-GENERATED DISCLAIMER: DATA IS SUBJECT TO AUDIT.
            </div>
        </div>
    );

    const renderReportBody = () => {
        switch (reportType) {
            case 'Resource':
                return (
                    <div className="preview-body">
                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px', marginBottom: '15px' }}>
                            <div className="preview-stat-block">
                                <div style={{ fontSize: '0.7rem', color: '#64748b' }}>AVERAGE PRODUCTIVITY</div>
                                <div style={{ fontSize: '1.25rem', fontWeight: 900 }}>88%</div>
                            </div>
                            <div className="preview-stat-block">
                                <div style={{ fontSize: '0.7rem', color: '#64748b' }}>EQUIPMENT IDLE TIME</div>
                                <div style={{ fontSize: '1.25rem', fontWeight: 900, color: '#ef4444' }}>14%</div>
                            </div>
                        </div>
                        <div className="preview-table">
                            <div className="table-row-h"><span>Equipment</span><span>Runtime</span><span>Idle</span></div>
                            <div className="table-row"><span>Concrete Mixer</span><span>6.5h</span><span>1.5h</span></div>
                            <div className="table-row"><span>Excavator</span><span>4.0h</span><span>4.0h</span></div>
                        </div>
                    </div>
                );
            case 'Instruction':
                return (
                    <div className="preview-body">
                        <div className="preview-text-block">
                            <div style={{ fontWeight: 800, fontSize: '0.85rem', color: '#2563eb' }}>Instruction #CIV-202: Beam Reinforcement</div>
                            <div style={{ fontSize: '0.75rem', marginTop: '4px' }}>Status: <span style={{ color: '#059669', fontWeight: 800 }}>COMPLIANT</span></div>
                        </div>
                        <div className="preview-text-block">
                            <div style={{ fontWeight: 800, fontSize: '0.85rem', color: '#f59e0b' }}>Issue #CIV-205: Curing delay in Block A</div>
                            <div style={{ fontSize: '0.75rem', marginTop: '4px' }}>Status: <span style={{ color: '#ef4444', fontWeight: 800 }}>ESCALATED TO PM</span></div>
                        </div>
                    </div>
                );
            case 'AI-Insight':
                return (
                    <div className="preview-body">
                        <div style={{ background: '#f0f9ff', padding: '15px', borderRadius: '12px', border: '1px solid #bae6fd', marginBottom: '15px' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', color: '#0369a1', fontWeight: 800, fontSize: '0.85rem' }}>
                                <Lightning size={18} weight="fill" /> RISK PREDICTION
                            </div>
                            <div style={{ fontSize: '0.8rem', marginTop: '8px', color: '#0c4a6e' }}>85% probability of slab delay due to upcoming storm window.</div>
                        </div>
                        <div style={{ background: '#fefce8', padding: '15px', borderRadius: '12px', border: '1px solid #fef3c7' }}>
                            <div style={{ fontWeight: 800, fontSize: '0.85rem', color: '#854d0e' }}>SUGGESTED ACTION</div>
                            <div style={{ fontSize: '0.8rem', marginTop: '8px', color: '#713f12' }}>Pre-cast beams in factory to offset site congestion bottlenecks.</div>
                        </div>
                    </div>
                );
            default:
                return (
                    <div className="preview-body" style={{ textAlign: 'center', padding: '2rem', color: '#94a3b8' }}>
                        <div style={{ fontSize: '0.85rem' }}>Full technical data for {reportType} report is being structured.</div>
                    </div>
                );
        }
    };

    const renderContent = () => {
        if (step === 1) {
            return (
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '1rem', padding: '5px' }}>
                    {reportTypes.map((type) => (
                        <button key={type.id} onClick={() => { setReportType(type.id); setStep(2); }} className="type-card" style={{ '--accent': type.color }}>
                            <div className="type-icon">{type.icon}</div>
                            <div style={{ textAlign: 'left' }}>
                                <div style={{ fontWeight: 800, fontSize: '0.9rem', color: '#0f172a' }}>{type.label}</div>
                                <div style={{ fontSize: '0.7rem', color: '#64748b', marginTop: '4px', lineHeight: 1.4 }}>{type.desc}</div>
                            </div>
                            <CaretRight size={18} className="arrow" />
                        </button>
                    ))}
                </div>
            );
        }

        return (
            <div style={{ display: 'grid', gridTemplateColumns: '320px 1fr', gap: '2rem' }}>
                {/* Configuration Panel */}
                <div style={{ borderRight: '1px solid #e2e8f0', paddingRight: '2rem' }}>
                    <h4 style={{ fontSize: '0.9rem', fontWeight: 800, marginBottom: '1.25rem', color: '#1e293b', display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <CalendarBlank size={18} weight="bold" /> REPORT FILTERS
                    </h4>

                    <div className="form-group">
                        <label>PROJECT / SITE</label>
                        <select value={config.project} onChange={(e) => setConfig({ ...config, project: e.target.value })}>
                            <option value="">Select Project</option>
                            {projects.map(p => <option key={p._id} value={p._id}>{p.name}</option>)}
                        </select>
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: '1.5fr 1fr', gap: '10px' }} className="form-group">
                        <div>
                            <label>REPORT FREQUENCY</label>
                            <select className="small-select" value={config.range} onChange={(e) => setConfig({ ...config, range: e.target.value })}>
                                {['Daily', 'Weekly', 'Monthly', 'Phase-wise'].map(f => <option key={f}>{f}</option>)}
                            </select>
                        </div>
                        <div>
                            <label>TRADE</label>
                            <select className="small-select" value={config.trade} onChange={(e) => setConfig({ ...config, trade: e.target.value })}>
                                {['Civil', 'MEP', 'Safety', 'Quality'].map(t => <option key={t}>{t}</option>)}
                            </select>
                        </div>
                    </div>

                    <div className="form-group">
                        <label>PRIORITY LEVEL</label>
                        <div style={{ display: 'flex', gap: '6px' }}>
                            {['Low', 'Medium', 'High', 'Critical'].map(p => (
                                <button key={p} onClick={() => setConfig({ ...config, priority: p })} className={`filter-pill ${config.priority === p ? 'active' : ''}`}>{p}</button>
                            ))}
                        </div>
                    </div>

                    <div className="form-group" style={{ marginTop: '20px' }}>
                        <label>OUTPUT FORMAT</label>
                        <div style={{ display: 'flex', gap: '10px' }}>
                            {[
                                { id: 'PDF', icon: <FilePdf size={20} color="#dc2626" /> },
                                { id: 'EXCEL', icon: <FileXls size={20} color="#059669" /> },
                                { id: 'CSV', icon: <FileCsv size={20} color="#64748b" /> }
                            ].map(fmt => (
                                <button
                                    key={fmt.id}
                                    onClick={() => setConfig({ ...config, format: fmt.id })}
                                    style={{
                                        flex: 1, padding: '10px', borderRadius: '10px', border: config.format === fmt.id ? '2px solid #2563eb' : '1px solid #e2e8f0',
                                        background: config.format === fmt.id ? '#eff6ff' : 'white', cursor: 'pointer', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '4px'
                                    }}
                                >
                                    {fmt.icon}
                                    <span style={{ fontSize: '0.65rem', fontWeight: 800 }}>{fmt.id}</span>
                                </button>
                            ))}
                        </div>
                    </div>
                </div>

                {/* Preview Panel */}
                <div style={{ display: 'flex', flexDirection: 'column' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
                        <h4 style={{ fontSize: '0.9rem', fontWeight: 800, color: '#64748b', margin: 0 }}>OFFICIAL DOCUMENT PREVIEW</h4>
                        <span style={{ fontSize: '0.7rem', fontWeight: 800, background: '#f8fafc', border: '1px solid #e2e8f0', padding: '4px 12px', borderRadius: '20px' }}>DRAFT v1.2</span>
                    </div>

                    <div className="report-canvas">
                        {renderReportHeader()}
                        <div style={{ padding: '20px', background: 'white' }}>
                            {renderReportBody()}
                        </div>
                        {renderReportFooter()}
                    </div>
                </div>
            </div>
        );
    };

    return (
        <div style={{ position: 'fixed', top: 0, left: 0, width: '100%', height: '100%', background: 'rgba(0,0,0,0.4)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1200, backdropFilter: 'blur(10px)' }}>
            <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} style={{ width: step === 1 ? '800px' : '1100px', maxHeight: '92vh', background: 'white', borderRadius: '32px', overflow: 'hidden', boxShadow: '0 40px 80px -15px rgba(0,0,0,0.5)', display: 'flex', flexDirection: 'column' }}>

                {/* Header Toolset */}
                <div style={{ padding: '1.25rem 2rem', borderBottom: '1px solid #f1f5f9', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#fcfcfe' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '15px' }}>
                        <div style={{ width: '42px', height: '42px', borderRadius: '12px', background: '#2563eb', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white', boxShadow: '0 4px 10px rgba(37, 99, 235, 0.3)' }}>
                            <FileText size={24} weight="fill" />
                        </div>
                        <div>
                            <h2 style={{ fontSize: '1.15rem', fontWeight: 900, color: '#0f172a', margin: 0 }}>Report Center</h2>
                            <div style={{ display: 'flex', gap: '10px', marginTop: '2px' }}>
                                <span style={{ fontSize: '0.75rem', fontWeight: 700, color: '#2563eb' }}>ENGINEER MODE</span>
                                <span style={{ fontSize: '0.75rem', color: '#cbd5e1' }}>•</span>
                                <span style={{ fontSize: '0.75rem', fontWeight: 700, color: '#64748b' }}>{step === 1 ? 'SELECT FRAMEWORK' : 'DYNAMIC CONFIG'}</span>
                            </div>
                        </div>
                    </div>
                    {step === 2 && <button onClick={() => setStep(1)} className="btn-back">← Back to Selection</button>}
                    <button onClick={onClose} style={{ width: '36px', height: '36px', borderRadius: '50%', border: 'none', background: '#f1f5f9', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><X size={20} weight="bold" /></button>
                </div>

                {/* Content Area */}
                <div style={{ flex: 1, padding: '2rem', overflowY: 'auto' }}>
                    {renderContent()}
                </div>

                {/* Submit Workflow Footer */}
                {step === 2 && (
                    <div style={{ padding: '1.5rem 2rem', background: '#f8fafc', borderTop: '1px solid #f1f5f9', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', color: '#64748b', fontSize: '0.8rem', fontWeight: 800 }}>
                            <PaperPlaneTilt size={20} weight="bold" color="#2563eb" /> AUTO-NOTIFY BUILDER ON SUBMIT
                        </div>
                        <div style={{ display: 'flex', gap: '12px' }}>
                            <button className="btn-secondary" style={{ width: '120px' }}>Save Draft</button>
                            <button onClick={handleGenerate} className="btn-primary" disabled={isGenerating || !config.project} style={{ minWidth: '220px', background: isGenerating ? '#94a3b8' : '#2563eb' }}>
                                {isGenerating ? 'Structuring Report...' : `Submit for Review (${config.format})`}
                                {!isGenerating && <DownloadSimple size={20} weight="bold" />}
                            </button>
                        </div>
                    </div>
                )}
            </motion.div>

            <style>{`
                .type-card { display: flex; align-items: center; gap: 1rem; padding: 1.25rem; background: #fff; border: 1px solid #f1f5f9; border-radius: 18px; cursor: pointer; transition: all 0.3s ease; position: relative; }
                .type-card:hover { border-color: var(--accent); transform: translateY(-3px); box-shadow: 0 10px 20px -5px rgba(0,0,0,0.06); }
                .type-icon { width: 44px; height: 44px; border-radius: 12px; background: #f8fafc; display: flex; align-items: center; justify-content: center; color: var(--accent); }
                .type-card:hover .type-icon { background: var(--accent); color: #fff; }
                .filter-pill { padding: 6px 12px; border-radius: 8px; border: 1px solid #e2e8f0; background: #fff; font-size: 0.7rem; font-weight: 800; color: #64748b; cursor: pointer; transition: all 0.2s; }
                .filter-pill.active { background: #2563eb; color: #fff; border-color: #2563eb; }
                .form-group label { display: block; font-size: 0.65rem; font-weight: 900; color: #94a3b8; margin-bottom: 6px; letter-spacing: 0.5px; }
                .form-group select, .form-group input { width: 100%; padding: 10px; border-radius: 10px; border: 1px solid #e2e8f0; font-size: 0.85rem; background: #fcfcfe; }
                .report-canvas { border-radius: 12px; box-shadow: 0 10px 30px rgba(0,0,0,0.1); border: 1px solid #e2e8f0; }
                .preview-stat-block { padding: 15px; border: 1px solid #e2e8f0; border-radius: 10px; }
                .preview-table { border: 1px solid #f1f5f9; border-radius: 8px; overflow: hidden; }
                .table-row-h { display: grid; grid-template-columns: 2fr 1fr 1fr; padding: 8px 12px; background: #f8fafc; font-size: 0.7rem; font-weight: 900; color: #64748b; }
                .table-row { display: grid; grid-template-columns: 2fr 1fr 1fr; padding: 8px 12px; border-bottom: 1px solid #f8fafc; font-size: 0.8rem; }
                .preview-text-block { padding: 12px; background: #fcfcfe; border-radius: 10px; border: 1px solid #f1f5f9; margin-bottom: 10px; }
                .btn-primary { padding: 12px 24px; border-radius: 14px; color: #fff; font-weight: 800; display: flex; align-items: center; gap: 10px; border: none; cursor: pointer; transition: all 0.2s; }
                .btn-secondary { padding: 12px 24px; border-radius: 14px; background: #fff; border: 1.5px solid #e2e8f0; color: #475569; font-weight: 800; cursor: pointer; }
                .btn-back { background: transparent; border: 1px solid #e2e8f0; padding: 6px 12px; border-radius: 8px; font-size: 0.75rem; font-weight: 700; color: #64748b; cursor: pointer; }
            `}</style>
        </div>
    );
};

export default GenerateReportModal;
